### ISSUE TITLE
Ssl error

### ISSUE THREAD

**Issue by djlazz3** [pandurang90/cloudconvert#14]
I get this error in my command prompt when i run my rb file

C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:921:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certi
        from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
        from C:/Ruby200-x64/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
        from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:921:in `connect'
        from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
        from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:851:in `start'
        from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:1373:in `request'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cloudconvert-0.0.5/lib/cloudconvert/conversion.rb:76:in `conversion_post_request'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cloudconvert-0.0.5/lib/cloudconvert/conversion.rb:80:in `start_conversion'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cloudconvert-0.0.5/lib/cloudconvert/conversion.rb:15:in `convert'
        from converter.rb:19:in `<main>'

I also have a file that stores the path of the file to be converted as well as the input/output filetype
For Reference this is the ruby file that im running:

require "cloudconvert"
x = 0
y = {}
File.open("C:/temp/tempfile.txt", "r" ) do |f|
f.each_line do |l| 
y[x] = l
x+=1
end
end
#y[0] = file path
#y[1] = input format
#y[2] = output format

Cloudconvert.configure do |config|
    config.api_key  = "5FQkFV4PhYrWkZ7Zn1HCRT_NJV945FyNzdimx2gSR2yK6x_QkFueDICsnKW9hTofHRY0E2MGmIk2N5HjDKmfew"
end
conversion = Cloudconvert::Conversion.new

conversion.convert("png", "jpg", y[0])

conversion.download_link

**Comment by pandurang90** [comment]
@djlazz3 
Do you have SSL_CERT_FILE set on your machine? I believe you are getting this error because of that.
Make sure you have cacert.pem downloaded and then set path 

```bash
    set SSL_CERT_FILE= path_your_cacert_pem_file
```

You can download cacert.pem file from http://curl.haxx.se/ca/cacert.pem

Check if this solves your problem.

**Comment by djlazz3** [comment]
I tried doing that just in case it wasn't set on my computer, but nothing changed in the output of the cmd.

Thanks for the help @pandurang90

**Comment by kapildewade** [comment]
@djlazz3 
Try this

brew update and brew upgrade openssl
brew link --force openssl
